name: test
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    #container:
    #   image: node:22
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      - name: Check format
        run: |
          cd frontend
          npx prettier --check .
      - name: Run lint
        run: |
          cd frontend
          npm run lint
      - name: Run tests
        run: |
          cd frontend 
          npm test
      - name: Build
        run: |
          cd frontend
          npm run build
